[package]
name = "custom-control"
version = "1.0.0"
authors = ["Rodrigo Cesar de Freitas Dias <rcesar@gmail.com>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
winsafe = { version = "0.0.11", features = ["gui"] }
