[package]
name = "combo-and-radios"
version = "1.0.0"
authors = ["Rodrigo Cesar de Freitas Dias <rcesar@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
winsafe = "0.0.4"
