[package]
name = "resizable-layout"
version = "1.0.0"
authors = ["Rodrigo César de Freitas Dias <rcesar@gmail.com>"]
edition = "2024"

[profile.release]
lto = true
strip = true
codegen-units = 1

[dependencies]
winsafe = { version = "0.0.25", features = ["gui"] }
